###################################################
# Dockerfile to build a Python environment
# with OGGM installed, based on Ubuntu 21.10.
###################################################

FROM xxEMPTY_TAG

m4_include(`Dockerfile_final.inc')
