###################################################
# Dockerfile to build a Python environment
# with OGGM installed, based on Ubuntu 22.04.
###################################################

m4_include(`Dockerfile_dev.in')

m4_include(`Dockerfile_empty.in')

m4_include(`Dockerfile_final.inc')
