FROM ubuntu:24.04

RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y install --no-install-recommends \
        fontconfig \
        fonts-dejavu \
        libfreetype6 \
        netcdf-bin \
        libtiff6 \
        libpng16-16t64 \
        libhdf4-0 \
        libhdf5-103-1t64 libhdf5-hl-100t64 libhdf5-cpp-103-1t64 libhdf5-hl-cpp-100t64 libhdf5-hl-fortran-100t64  \
        libqhull8.0 \
        libqhull-r8.0 \
        libxml2 \
        libgif7 \
        libjpeg8 \
        libjpeg-turbo8 \
        libopenjp2-7 \
        libwebp7 \
        libjson-c5 \
        libgeos-c1v5 \
        liblapack3 \
        libopenblas0 \
        libagg2 \
        libdb5.3 \
        libexpat1 \
        libffi8 \
        libbz2-1.0 \
        liblzma5 \
        libblosc1 \
        libbrotli1 \
        liblcms2-2 \
        libjxr0 \
        liblz4-1 \
        libsnappy1v5 \
        libzopfli1 \
        libxcb1 \
        libllvm14 \
        libgomp1 \
        sqlite3 \
        curl \
        git \
        locales \
        less \
        nano \
        ca-certificates && \
    apt-get -y purge gnupg && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    locale-gen en_US.UTF-8 && \
    echo /opt/proj/lib > /etc/ld.so.conf.d/optproj.conf && \
    ldconfig

ENV \
    PATH=/usr/local/pyenv/shims:/usr/local/pyenv/bin:/opt/proj/bin:$PATH \
    LIBRARY_PATH=/opt/proj/lib \
    PROJ_NETWORK=ON \
    PROJ_DIR=/opt/proj \
    PROJ_LIB=/opt/proj/share/proj \
    PYENV_ROOT=/usr/local/pyenv \
    m4_ifelse(m4_index(xxPYTHON_VERSION, pyston), 0, SETUPTOOLS_USE_DISTUTILS=stdlib) \
    PIP=pip \
    LANG=en_US.UTF-8
