sudo: required

services:
 - docker

env:
 - PY_VER=3
 - PY_VER=2

script:
 - set -e
 - export PY_SFX="$([ "$PY_VER" == "2" ] && echo 2)"
 - docker pull ubuntu:16.04
 - ./build_image.sh "base${PY_SFX}"
 - ./build_image.sh "jupyter${PY_SFX}"

after_success:
 - set -e
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push "oggm/base${PY_SFX}"
 - docker push "oggm/jupyter${PY_SFX}"
