sudo: required

services:
 - docker

env:
 - DF_BUILD_BASE_DIR=base
 - DF_BUILD_BASE_DIR=base2

script:
 - set -e
 - export OGGM_COMMIT="$(cat oggm_commit.txt)"
 - export REPO="oggm/${DF_BUILD_BASE_DIR}"
 - export TAG="$([ "$TRAVIS_BRANCH" == "master" ] && echo "latest" || echo $TRAVIS_BRANCH)"
 - cd "${DF_BUILD_BASE_DIR}"
 - docker pull "${REPO}"
 - docker pull ubuntu:16.04
 - docker build -f Dockerfile -t "${REPO}:${OGGM_COMMIT}" .
 - docker run "${REPO}:${OGGM_COMMIT}" /bin/bash -c 'eval ${OGGM_DOCKER_TEST_COMMAND}'

after_success:
 - set -e
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker tag "${REPO}:${OGGM_COMMIT}" "${REPO}:${TAG}"
 - docker tag "${REPO}:${OGGM_COMMIT}" "${REPO}:travis-${TRAVIS_BUILD_NUMBER}"
 - docker push "${REPO}"

