on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * 0'

jobs:
  build-py39:
    runs-on: ubuntu-latest
    name: Build Python 3.9 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py39
      id: untested-base-py39
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base/
        build_args: PYTHON_VERSION=3.9
        name: oggm/untested_base
        tags: py39,latest
        date_tag: true
        force_pull: true
    - name: Build base:py39
      id: base-py39
      uses: OGGM/docker-build-and-push-action@v2
      with:
        path: ./base/
        name: oggm/base
        no_push: true
        tmp_tag: 'base:test'
    - name: Test base:py39
      id: test-base-py39
      run: docker run --rm base:test /root/test.sh
    - name: Push base:py39
      id: push-base-py39
      uses: OGGM/docker-build-and-push-action@v2
      with:
        path: ./base/
        name: oggm/base
        no_cache: false
        date_tag: true
    - name: Trigger OGGM
      id: trigger-oggm
      uses: OGGM/repo-dispatch-action@v1
      with:
        repo: OGGM/oggm
        auth_user: ${{ secrets.DispatchUser }}
        auth_secret: ${{ secrets.DispatchSecret }}
        action: build-docker-image
  build-py37:
    runs-on: ubuntu-latest
    name: Build Python 3.7 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py37
      id: untested-base-py37
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base/
        build_args: PYTHON_VERSION=3.7
        name: oggm/untested_base
        tags: py37
        force_pull: true
  build-py38:
    runs-on: ubuntu-latest
    name: Build Python 3.8 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py38
      id: untested-base-py38
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base/
        build_args: PYTHON_VERSION=3.8
        name: oggm/untested_base
        tags: py38
        force_pull: true
  build-pyston:
    runs-on: ubuntu-latest
    name: Build Pyston Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:pyston
      id: untested-base-pyston
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base/
        build_args: PYTHON_VERSION=pyston
        name: oggm/untested_base
        tags: pyston
        force_pull: true
