on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * 0'

jobs:
  build-py37:
    runs-on: ubuntu-latest
    name: Build Python 3.7 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py37
      id: untested-base-py37
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base_py37/
        name: oggm/untested_base
        tags: py37,latest
        date_tag: true
        force_pull: true
    - name: Build base:py37
      id: base-py37
      uses: OGGM/docker-build-and-push-action@v2
      with:
        path: ./base/
        name: oggm/base
        no_push: true
        tmp_tag: 'base:test'
    - name: Test base:py37
      id: test-base-py37
      run: docker run --rm base:test /root/test.sh
    - name: Push base:py37
      id: push-base-py37
      uses: OGGM/docker-build-and-push-action@v2
      with:
        path: ./base/
        name: oggm/base
        no_cache: false
        date_tag: true
    - name: Trigger OGGM
      id: trigger-oggm
      uses: OGGM/repo-dispatch-action@v1
      with:
        repo: OGGM/oggm
        auth_user: ${{ secrets.DispatchUser }}
        auth_secret: ${{ secrets.DispatchSecret }}
        action: build-docker-image
  build-py36:
    runs-on: ubuntu-latest
    name: Build Python 3.6 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py36
      id: untested-base-py36
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base_py36/
        name: oggm/untested_base
        tags: py36
        force_pull: true
  build-py38:
    runs-on: ubuntu-latest
    name: Build Python 3.8 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py38
      id: untested-base-py38
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base_py38/
        name: oggm/untested_base
        tags: py38
        force_pull: true
  build-py39:
    runs-on: ubuntu-latest
    name: Build Python 3.9 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:py39
      id: untested-base-py39
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base_py39/
        name: oggm/untested_base
        tags: py39
        force_pull: true
  build-pypy36:
    runs-on: ubuntu-latest
    name: Build Pypy 3.6 Images
    steps:
    - uses: actions/checkout@v2
    - name: Build untested_base:pypy36
      id: untested-base-pypy36
      uses: OGGM/docker-build-and-push-action@v2
      with:
        user: ${{ secrets.DockerhubUser }}
        pass: ${{ secrets.DockerhubPass }}
        path: ./untested_base_pypy36/
        name: oggm/untested_base
        tags: pypy36
        force_pull: true
